CREATE TABLE `boat_routes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`type` enum('speedboat','ferry') NOT NULL,
	`fromLocation` varchar(255) NOT NULL,
	`toLocation` varchar(255) NOT NULL,
	`fromLat` varchar(50) NOT NULL,
	`fromLng` varchar(50) NOT NULL,
	`toLat` varchar(50) NOT NULL,
	`toLng` varchar(50) NOT NULL,
	`distance` varchar(50),
	`duration` varchar(100) NOT NULL,
	`price` int NOT NULL,
	`schedule` text,
	`capacity` int NOT NULL,
	`amenities` text,
	`boatInfo` text,
	`description` text,
	`image` varchar(500),
	`published` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `boat_routes_id` PRIMARY KEY(`id`),
	CONSTRAINT `boat_routes_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `map_locations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`type` enum('island','resort','dive_site','surf_spot','atoll','city') NOT NULL,
	`latitude` varchar(50) NOT NULL,
	`longitude` varchar(50) NOT NULL,
	`description` text,
	`highlights` text,
	`amenities` text,
	`image` varchar(500),
	`icon` varchar(50),
	`color` varchar(20),
	`difficulty` varchar(50),
	`depth` varchar(50),
	`waveHeight` varchar(50),
	`rating` varchar(10),
	`reviews` int DEFAULT 0,
	`population` int,
	`priceRange` varchar(50),
	`bestSeason` varchar(100),
	`published` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `map_locations_id` PRIMARY KEY(`id`),
	CONSTRAINT `map_locations_slug_unique` UNIQUE(`slug`)
);
