CREATE TABLE `island_guides` (
	`id` int AUTO_INCREMENT NOT NULL,
	`locationId` int,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`atoll` varchar(255),
	`overview` text,
	`quickFacts` text,
	`flightInfo` text,
	`speedboatInfo` text,
	`ferryInfo` text,
	`topThingsToDo` text,
	`snorkelingGuide` text,
	`divingGuide` text,
	`surfWatersports` text,
	`sandbankDolphinTrips` text,
	`beachesLocalRules` text,
	`foodCafes` text,
	`currency` varchar(100),
	`language` varchar(100),
	`bestTimeToVisit` varchar(255),
	`whatToPack` text,
	`healthTips` text,
	`emergencyContacts` text,
	`threeDayItinerary` text,
	`fiveDayItinerary` text,
	`faq` text,
	`images` text,
	`latitude` varchar(50),
	`longitude` varchar(50),
	`metaTitle` varchar(255),
	`metaDescription` varchar(500),
	`metaKeywords` varchar(500),
	`focusKeyword` varchar(255),
	`seoScore` int,
	`published` int NOT NULL DEFAULT 0,
	`featured` int NOT NULL DEFAULT 0,
	`viewCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `island_guides_id` PRIMARY KEY(`id`),
	CONSTRAINT `island_guides_slug_unique` UNIQUE(`slug`)
);
