CREATE TABLE `seo_meta_tags` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contentType` enum('blog','package','island_guide','boat_route','map_location','home','about','contact') NOT NULL,
	`contentId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` varchar(500) NOT NULL,
	`keywords` text,
	`ogTitle` varchar(255),
	`ogDescription` varchar(500),
	`ogImage` varchar(500),
	`twitterCard` varchar(50),
	`canonicalUrl` varchar(500),
	`robotsIndex` varchar(20) DEFAULT 'index',
	`robotsFollow` varchar(20) DEFAULT 'follow',
	`focusKeyword` varchar(255),
	`status` enum('pending','approved','rejected','modified') NOT NULL DEFAULT 'pending',
	`confidence` int DEFAULT 0,
	`seoScore` int DEFAULT 0,
	`generatedBy` varchar(100),
	`approvedBy` int,
	`rejectionReason` text,
	`generatedAt` timestamp DEFAULT (now()),
	`approvedAt` timestamp,
	`version` int DEFAULT 1,
	`previousVersionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seo_meta_tags_id` PRIMARY KEY(`id`)
);
