CREATE TABLE `activity_spots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`islandGuideId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`spotType` enum('surf_spot','dive_site','snorkeling_spot') NOT NULL,
	`description` text,
	`difficulty` enum('beginner','intermediate','advanced') DEFAULT 'intermediate',
	`latitude` varchar(50),
	`longitude` varchar(50),
	`accessInfo` text,
	`bestSeason` varchar(255),
	`bestTime` varchar(100),
	`waterConditions` text,
	`maxDepth` int,
	`minDepth` int,
	`marineLife` text,
	`waveHeight` varchar(100),
	`waveType` varchar(100),
	`coralCoverage` varchar(100),
	`fishSpecies` text,
	`tips` text,
	`facilities` text,
	`images` text,
	`metaTitle` varchar(255),
	`metaDescription` varchar(500),
	`published` int NOT NULL DEFAULT 0,
	`featured` int NOT NULL DEFAULT 0,
	`displayOrder` int NOT NULL DEFAULT 0,
	`viewCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `activity_spots_id` PRIMARY KEY(`id`)
);
