CREATE TABLE `attraction_guides` (
	`id` int AUTO_INCREMENT NOT NULL,
	`placeId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`attractionType` enum('dive_site','surf_spot','snorkeling_spot','poi') NOT NULL,
	`overview` text,
	`quickFacts` text,
	`difficulty` enum('beginner','intermediate','advanced','expert'),
	`waterConditions` text,
	`bestSeason` varchar(255),
	`seasonalInfo` text,
	`depthRange` varchar(100),
	`waveHeight` varchar(100),
	`marineLife` text,
	`accessInfo` text,
	`nearestIsland` varchar(255),
	`distanceFromIsland` varchar(100),
	`facilities` text,
	`amenities` text,
	`safetyTips` text,
	`localRules` text,
	`restrictions` text,
	`typicalCost` varchar(100),
	`bookingInfo` text,
	`heroImage` varchar(500),
	`images` text,
	`videos` text,
	`latitude` varchar(50),
	`longitude` varchar(50),
	`metaTitle` varchar(255),
	`metaDescription` varchar(500),
	`metaKeywords` varchar(500),
	`focusKeyword` varchar(255),
	`seoScore` int,
	`published` int NOT NULL DEFAULT 0,
	`featured` int NOT NULL DEFAULT 0,
	`displayOrder` int NOT NULL DEFAULT 0,
	`viewCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `attraction_guides_id` PRIMARY KEY(`id`),
	CONSTRAINT `attraction_guides_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
ALTER TABLE `places` ADD `slug` varchar(255);--> statement-breakpoint
ALTER TABLE `places` ADD `latitude` decimal(10,6);--> statement-breakpoint
ALTER TABLE `places` ADD `longitude` decimal(10,6);--> statement-breakpoint
ALTER TABLE `places` ADD CONSTRAINT `places_slug_unique` UNIQUE(`slug`);