import { getDb } from "./db";
import { activitySpots } from "../drizzle/schema";

/**
 * Comprehensive activity spot data with difficulty levels, best seasons, and marine life
 * This seed script populates the database with detailed information about diving sites,
 * snorkeling spots, and surf breaks across the Maldives atolls.
 */

const activitySpotsData = [
  // ===== DIVING SITES =====
  // Kaafu Atoll
  {
    islandGuideId: 1,
    atollId: 1,
    name: "Banana Reef",
    slug: "banana-reef",
    spotType: "dive_site" as const,
    category: "House Reef",
    description: "One of the most famous dive sites in the Maldives, Banana Reef is a stunning coral formation that attracts divers of all levels. The site features vibrant coral gardens, abundant fish life, and excellent visibility.",
    difficulty: "beginner" as const,
    latitude: "4.1796",
    longitude: "73.5093",
    accessInfo: "Accessible by speedboat from Male, approximately 20 minutes",
    bestSeason: "November to April",
    bestTime: "Morning dives (6-10 AM)",
    waterConditions: "Calm waters, visibility 20-40m",
    maxDepth: 35,
    minDepth: 5,
    marineLife: JSON.stringify(["Reef sharks", "Groupers", "Snappers", "Parrotfish", "Angelfish", "Butterflyfish"]),
    waveHeight: null,
    waveType: null,
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Best visited in the morning for optimal visibility",
      "Watch for strong currents on the outer wall",
      "Bring a wide-angle lens for coral photography",
      "The site can get crowded during peak season"
    ]),
    facilities: JSON.stringify(["Dive shops nearby", "Restaurants", "Hotels"]),
    images: JSON.stringify(["/images/banana-reef.jpg"]),
    rating: "4.8",
    reviewCount: 245,
    capacity: 12,
    operatorInfo: JSON.stringify({ name: "Various operators", contact: "Available through resorts" }),
    metaTitle: "Banana Reef Diving Site - Kaafu Atoll, Maldives",
    metaDescription: "Explore Banana Reef, one of the most famous diving sites in the Maldives with vibrant coral gardens and abundant marine life.",
    published: 1,
    featured: 1,
    displayOrder: 1,
    viewCount: 0,
  },
  {
    islandGuideId: 2,
    atollId: 1,
    name: "Kandooma Thila",
    slug: "kandooma-thila",
    spotType: "dive_site" as const,
    category: "Thila Dive",
    description: "A spectacular thila (underwater mountain) dive site featuring a pinnacle that rises from 60m to 15m. Known for excellent visibility and encounters with large pelagic fish.",
    difficulty: "advanced" as const,
    latitude: "4.2100",
    longitude: "73.5200",
    accessInfo: "Requires liveaboard or day trip from resort",
    bestSeason: "March to May, September to November",
    bestTime: "Early morning dives",
    waterConditions: "Strong currents, visibility 25-50m",
    maxDepth: 60,
    minDepth: 15,
    marineLife: JSON.stringify(["Reef sharks", "Trevally", "Barracuda", "Snappers", "Groupers", "Fusiliers"]),
    waveHeight: null,
    waveType: null,
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Only for advanced divers with good buoyancy control",
      "Expect strong currents - use reef hooks if experienced",
      "Best during slack water periods",
      "Bring extra air supply for safety"
    ]),
    facilities: JSON.stringify(["Liveaboard support", "Emergency services"]),
    images: JSON.stringify(["/images/kandooma-thila.jpg"]),
    rating: "4.9",
    reviewCount: 189,
    capacity: 8,
    operatorInfo: JSON.stringify({ name: "Liveaboard operators", contact: "Various liveaboards" }),
    metaTitle: "Kandooma Thila - Advanced Diving in Kaafu Atoll",
    metaDescription: "Dive Kandooma Thila, an advanced dive site with strong currents, large pelagic fish, and spectacular coral formations.",
    published: 1,
    featured: 1,
    displayOrder: 2,
    viewCount: 0,
  },
  // Alif Alif Atoll
  {
    islandGuideId: 3,
    atollId: 2,
    name: "Manta Point",
    slug: "manta-point",
    spotType: "dive_site" as const,
    category: "Manta Ray Encounters",
    description: "World-renowned manta ray encounter site where seasonal aggregations of manta rays gather to feed. One of the most magical diving experiences in the world.",
    difficulty: "intermediate" as const,
    latitude: "4.3500",
    longitude: "73.4200",
    accessInfo: "Accessible by speedboat from Alif Alif resorts",
    bestSeason: "June to November (manta season)",
    bestTime: "Early morning, slack water periods",
    waterConditions: "Variable, visibility 15-30m",
    maxDepth: 25,
    minDepth: 5,
    marineLife: JSON.stringify(["Manta rays", "Reef sharks", "Trevally", "Snappers", "Jacks", "Groupers"]),
    waveHeight: null,
    waveType: null,
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Manta sightings not guaranteed but very likely during season",
      "Avoid touching or chasing mantas - observe from distance",
      "Use wide-angle lenses for best manta photography",
      "Current can be strong - stay near the reef"
    ]),
    facilities: JSON.stringify(["Resort support", "Dive guides", "Photography services"]),
    images: JSON.stringify(["/images/manta-point.jpg"]),
    rating: "4.9",
    reviewCount: 412,
    capacity: 10,
    operatorInfo: JSON.stringify({ name: "Resort dive centers", contact: "Alif Alif resorts" }),
    metaTitle: "Manta Point - Manta Ray Diving in Alif Alif Atoll",
    metaDescription: "Experience world-class manta ray encounters at Manta Point in Alif Alif Atoll during the seasonal aggregations.",
    published: 1,
    featured: 1,
    displayOrder: 3,
    viewCount: 0,
  },
  // Baa Atoll
  {
    islandGuideId: 4,
    atollId: 3,
    name: "Hanifaru Bay",
    slug: "hanifaru-bay",
    spotType: "dive_site" as const,
    category: "Manta & Whale Shark",
    description: "UNESCO Biosphere Reserve famous for massive seasonal gatherings of manta rays and whale sharks. A truly unique diving and snorkeling destination.",
    difficulty: "beginner" as const,
    latitude: "5.0500",
    longitude: "73.0500",
    accessInfo: "Speedboat from Baa Atoll resorts, 30-45 minutes",
    bestSeason: "June to November (manta season), March to May (whale sharks)",
    bestTime: "Early morning, slack water",
    waterConditions: "Plankton-rich, visibility 10-20m",
    maxDepth: 20,
    minDepth: 0,
    marineLife: JSON.stringify(["Manta rays", "Whale sharks", "Reef sharks", "Trevally", "Fusiliers", "Snappers"]),
    waveHeight: null,
    waveType: null,
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Protected area - follow all regulations",
      "Snorkeling is often better than diving here",
      "Bring polarized sunglasses for spotting from surface",
      "Plankton blooms reduce visibility but attract mantas"
    ]),
    facilities: JSON.stringify(["Resort support", "Snorkel guides", "Photography services"]),
    images: JSON.stringify(["/images/hanifaru-bay.jpg"]),
    rating: "4.9",
    reviewCount: 523,
    capacity: 12,
    operatorInfo: JSON.stringify({ name: "Baa Atoll resorts", contact: "UNESCO protected area" }),
    metaTitle: "Hanifaru Bay - Manta Rays & Whale Sharks in Baa Atoll",
    metaDescription: "Dive and snorkel at Hanifaru Bay, a UNESCO Biosphere Reserve with seasonal manta ray and whale shark aggregations.",
    published: 1,
    featured: 1,
    displayOrder: 4,
    viewCount: 0,
  },
  // Vaavu Atoll
  {
    islandGuideId: 5,
    atollId: 4,
    name: "Equatorial Channel",
    slug: "equatorial-channel",
    spotType: "dive_site" as const,
    category: "Drift Dive",
    description: "Thrilling drift dive through a channel with strong currents and abundant pelagic fish. One of the most exciting dives in the Maldives.",
    difficulty: "advanced" as const,
    latitude: "3.9800",
    longitude: "73.0200",
    accessInfo: "Liveaboard or day trip from Vaavu resorts",
    bestSeason: "March to May, September to November",
    bestTime: "Slack water periods",
    waterConditions: "Strong currents, visibility 20-40m",
    maxDepth: 40,
    minDepth: 10,
    marineLife: JSON.stringify(["Reef sharks", "Trevally", "Barracuda", "Snappers", "Groupers", "Jacks"]),
    waveHeight: null,
    waveType: null,
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Advanced divers only - strong current experience required",
      "Use reef hooks for safety",
      "Dive during slack water for best experience",
      "Bring extra air and dive computer"
    ]),
    facilities: JSON.stringify(["Liveaboard support", "Emergency services"]),
    images: JSON.stringify(["/images/equatorial-channel.jpg"]),
    rating: "4.8",
    reviewCount: 156,
    capacity: 8,
    operatorInfo: JSON.stringify({ name: "Liveaboard operators", contact: "Various liveaboards" }),
    metaTitle: "Equatorial Channel - Advanced Drift Diving in Vaavu",
    metaDescription: "Experience thrilling drift diving at Equatorial Channel with strong currents and abundant pelagic fish.",
    published: 1,
    featured: 1,
    displayOrder: 5,
    viewCount: 0,
  },
  // Alif Dhaal Atoll
  {
    islandGuideId: 6,
    atollId: 5,
    name: "Whale Shark Point",
    slug: "whale-shark-point",
    spotType: "dive_site" as const,
    category: "Whale Shark Encounters",
    description: "Seasonal whale shark encounters in a protected area. Excellent snorkeling and diving opportunities to observe these gentle giants.",
    difficulty: "beginner" as const,
    latitude: "3.8500",
    longitude: "73.1500",
    accessInfo: "Speedboat from Alif Dhaal resorts, 20-30 minutes",
    bestSeason: "March to May (peak season)",
    bestTime: "Early morning",
    waterConditions: "Plankton-rich, visibility 10-20m",
    maxDepth: 25,
    minDepth: 0,
    marineLife: JSON.stringify(["Whale sharks", "Reef sharks", "Trevally", "Snappers", "Jacks", "Fusiliers"]),
    waveHeight: null,
    waveType: null,
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Snorkeling is often better than diving",
      "Whale sharks not guaranteed but likely during season",
      "Maintain 4m distance from whale sharks",
      "Bring underwater camera for memorable shots"
    ]),
    facilities: JSON.stringify(["Resort support", "Snorkel guides", "Photography services"]),
    images: JSON.stringify(["/images/whale-shark-point.jpg"]),
    rating: "4.8",
    reviewCount: 287,
    capacity: 12,
    operatorInfo: JSON.stringify({ name: "Alif Dhaal resorts", contact: "Protected area" }),
    metaTitle: "Whale Shark Point - Encounter Whale Sharks in Alif Dhaal",
    metaDescription: "Snorkel and dive with whale sharks at Whale Shark Point during the seasonal aggregations in Alif Dhaal Atoll.",
    published: 1,
    featured: 1,
    displayOrder: 6,
    viewCount: 0,
  },
  // Addu Atoll
  {
    islandGuideId: 7,
    atollId: 6,
    name: "Equatorial Channel South",
    slug: "equatorial-channel-south",
    spotType: "dive_site" as const,
    category: "Drift Dive",
    description: "Advanced drift dive in the southernmost atoll with world-class diving conditions and abundant marine life.",
    difficulty: "advanced" as const,
    latitude: "0.6200",
    longitude: "73.1800",
    accessInfo: "Liveaboard or day trip from Addu resorts",
    bestSeason: "March to May, September to November",
    bestTime: "Slack water periods",
    waterConditions: "Strong currents, visibility 25-45m",
    maxDepth: 50,
    minDepth: 15,
    marineLife: JSON.stringify(["Reef sharks", "Trevally", "Barracuda", "Snappers", "Groupers", "Jacks"]),
    waveHeight: null,
    waveType: null,
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Advanced divers only",
      "Excellent for large pelagic encounters",
      "Use reef hooks for safety",
      "Dive during slack water"
    ]),
    facilities: JSON.stringify(["Liveaboard support", "Emergency services"]),
    images: JSON.stringify(["/images/equatorial-channel-south.jpg"]),
    rating: "4.9",
    reviewCount: 134,
    capacity: 8,
    operatorInfo: JSON.stringify({ name: "Liveaboard operators", contact: "Various liveaboards" }),
    metaTitle: "Equatorial Channel South - World-Class Diving in Addu",
    metaDescription: "Dive Equatorial Channel South in Addu Atoll with world-class conditions and abundant marine life.",
    published: 1,
    featured: 1,
    displayOrder: 7,
    viewCount: 0,
  },

  // ===== SNORKELING SPOTS =====
  {
    islandGuideId: 1,
    atollId: 1,
    name: "House Reef Snorkel",
    slug: "house-reef-snorkel",
    spotType: "snorkeling_spot" as const,
    category: "House Reef",
    description: "Excellent snorkeling directly from the resort beach with vibrant coral gardens and abundant tropical fish.",
    difficulty: "beginner" as const,
    latitude: "4.1796",
    longitude: "73.5093",
    accessInfo: "Direct access from resort beach",
    bestSeason: "November to April",
    bestTime: "Morning (6-10 AM) or late afternoon (3-5 PM)",
    waterConditions: "Calm, visibility 15-25m",
    maxDepth: 10,
    minDepth: 0,
    marineLife: null,
    waveHeight: null,
    waveType: null,
    coralCoverage: "90%",
    fishSpecies: JSON.stringify(["Parrotfish", "Angelfish", "Butterflyfish", "Snappers", "Groupers", "Wrasses"]),
    tips: JSON.stringify([
      "Wear reef-safe sunscreen",
      "Avoid touching coral",
      "Best visibility in the morning",
      "Bring an underwater camera"
    ]),
    facilities: JSON.stringify(["Resort amenities", "Snorkel rental", "Lifeguard"]),
    images: JSON.stringify(["/images/house-reef-snorkel.jpg"]),
    rating: "4.7",
    reviewCount: 312,
    capacity: 50,
    operatorInfo: JSON.stringify({ name: "Resort snorkel center", contact: "Available daily" }),
    metaTitle: "House Reef Snorkeling - Kaafu Atoll",
    metaDescription: "Snorkel the vibrant house reef with tropical fish and coral gardens directly from the resort.",
    published: 1,
    featured: 1,
    displayOrder: 8,
    viewCount: 0,
  },
  {
    islandGuideId: 4,
    atollId: 3,
    name: "Hanifaru Snorkel",
    slug: "hanifaru-snorkel",
    spotType: "snorkeling_spot" as const,
    category: "Manta & Whale Shark",
    description: "Snorkel with manta rays and whale sharks in this UNESCO protected area. Often better than diving for marine megafauna encounters.",
    difficulty: "beginner" as const,
    latitude: "5.0500",
    longitude: "73.0500",
    accessInfo: "Speedboat from Baa Atoll resorts, 30-45 minutes",
    bestSeason: "June to November (manta), March to May (whale sharks)",
    bestTime: "Early morning",
    waterConditions: "Plankton-rich, visibility 10-20m",
    maxDepth: 5,
    minDepth: 0,
    marineLife: null,
    waveHeight: null,
    waveType: null,
    coralCoverage: "Moderate",
    fishSpecies: JSON.stringify(["Manta rays", "Whale sharks", "Reef sharks", "Trevally", "Fusiliers"]),
    tips: JSON.stringify([
      "Follow all protected area regulations",
      "Maintain 4m distance from whale sharks",
      "Bring polarized sunglasses",
      "Plankton blooms attract mantas"
    ]),
    facilities: JSON.stringify(["Resort support", "Snorkel guides", "Photography services"]),
    images: JSON.stringify(["/images/hanifaru-snorkel.jpg"]),
    rating: "4.9",
    reviewCount: 487,
    capacity: 20,
    operatorInfo: JSON.stringify({ name: "Baa Atoll resorts", contact: "UNESCO protected area" }),
    metaTitle: "Hanifaru Snorkeling - Manta Rays & Whale Sharks",
    metaDescription: "Snorkel with manta rays and whale sharks at Hanifaru Bay in Baa Atoll.",
    published: 1,
    featured: 1,
    displayOrder: 9,
    viewCount: 0,
  },

  // ===== SURFING SPOTS =====
  {
    islandGuideId: 8,
    atollId: 7,
    name: "Pasta Point",
    slug: "pasta-point",
    spotType: "surf_spot" as const,
    category: "Beginner Waves",
    description: "One of the most famous and consistent beginner-friendly surf breaks in the Maldives. Perfect for learning to surf.",
    difficulty: "beginner" as const,
    latitude: "3.6500",
    longitude: "72.8300",
    accessInfo: "Speedboat from Laamu resorts, 15-20 minutes",
    bestSeason: "March to October (SW monsoon)",
    bestTime: "Early morning (6-10 AM), late afternoon (3-6 PM)",
    waterConditions: "Warm water, consistent swells",
    maxDepth: null,
    minDepth: null,
    marineLife: null,
    waveHeight: "2-4 feet",
    waveType: "Beach break",
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Perfect for beginners and intermediate surfers",
      "Consistent waves year-round",
      "Warm water - minimal wetsuit needed",
      "Bring reef booties for protection"
    ]),
    facilities: JSON.stringify(["Surf school", "Board rental", "Restaurant", "Accommodation"]),
    images: JSON.stringify(["/images/pasta-point.jpg"]),
    rating: "4.8",
    reviewCount: 267,
    capacity: 20,
    operatorInfo: JSON.stringify({ name: "Pasta Point Surf Resort", contact: "Laamu Atoll" }),
    metaTitle: "Pasta Point - Best Beginner Surf Break in Maldives",
    metaDescription: "Learn to surf at Pasta Point, the most famous beginner-friendly surf break in the Maldives.",
    published: 1,
    featured: 1,
    displayOrder: 10,
    viewCount: 0,
  },
  {
    islandGuideId: 9,
    atollId: 8,
    name: "Chickens",
    slug: "chickens-surf-spot",
    spotType: "surf_spot" as const,
    category: "Intermediate Waves",
    description: "Consistent reef break with quality waves for intermediate surfers. Named for the local chickens that roam the area.",
    difficulty: "intermediate" as const,
    latitude: "3.5800",
    longitude: "72.8100",
    accessInfo: "Speedboat from Laamu resorts, 20-25 minutes",
    bestSeason: "March to October (SW monsoon)",
    bestTime: "Morning and late afternoon",
    waterConditions: "Warm, consistent swells",
    maxDepth: null,
    minDepth: null,
    marineLife: null,
    waveHeight: "3-5 feet",
    waveType: "Reef break",
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Good for intermediate surfers",
      "Reef break - wear reef booties",
      "Can get crowded during peak season",
      "Watch for sharp coral"
    ]),
    facilities: JSON.stringify(["Nearby resort", "Board rental", "Restaurant"]),
    images: JSON.stringify(["/images/chickens-surf.jpg"]),
    rating: "4.6",
    reviewCount: 189,
    capacity: 15,
    operatorInfo: JSON.stringify({ name: "Local operators", contact: "Laamu Atoll" }),
    metaTitle: "Chickens Surf Spot - Intermediate Reef Break",
    metaDescription: "Surf Chickens, a consistent reef break in Laamu Atoll perfect for intermediate surfers.",
    published: 1,
    featured: 1,
    displayOrder: 11,
    viewCount: 0,
  },
  {
    islandGuideId: 10,
    atollId: 9,
    name: "Arugambe",
    slug: "arugambe-surf-spot",
    spotType: "surf_spot" as const,
    category: "Advanced Waves",
    description: "Powerful reef break with heavy waves for advanced surfers. One of the most challenging and rewarding breaks in the Maldives.",
    difficulty: "advanced" as const,
    latitude: "3.4200",
    longitude: "72.7900",
    accessInfo: "Speedboat from Laamu resorts, 30-35 minutes",
    bestSeason: "March to October (SW monsoon)",
    bestTime: "Morning (6-10 AM)",
    waterConditions: "Powerful swells, strong currents",
    maxDepth: null,
    minDepth: null,
    marineLife: null,
    waveHeight: "5-8 feet",
    waveType: "Reef break",
    coralCoverage: null,
    fishSpecies: null,
    tips: JSON.stringify([
      "Advanced surfers only",
      "Heavy, powerful waves",
      "Strong currents - be prepared",
      "Reef booties essential",
      "Respect local surfers"
    ]),
    facilities: JSON.stringify(["Nearby resort", "Board rental", "Emergency services"]),
    images: JSON.stringify(["/images/arugambe-surf.jpg"]),
    rating: "4.7",
    reviewCount: 145,
    capacity: 10,
    operatorInfo: JSON.stringify({ name: "Local operators", contact: "Laamu Atoll" }),
    metaTitle: "Arugambe - Advanced Surf Break in Maldives",
    metaDescription: "Challenge yourself at Arugambe, a powerful advanced reef break in Laamu Atoll.",
    published: 1,
    featured: 1,
    displayOrder: 12,
    viewCount: 0,
  },
];

/**
 * Seed the activity spots table with comprehensive data
 */
export async function seedActivitySpots() {
  try {
    console.log("Seeding activity spots...");
    
    // Get database connection
    const db = await getDb();
    if (!db) {
      throw new Error("Failed to connect to database");
    }
    
    // Insert all activity spots
    const result = await db.insert(activitySpots).values(activitySpotsData);
    
    console.log(`✓ Successfully seeded ${activitySpotsData.length} activity spots`);
    return result;
  } catch (error) {
    console.error("Error seeding activity spots:", error);
    throw error;
  }
}

// Run seed if executed directly
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

if (import.meta.url === `file://${process.argv[1]}`) {
  seedActivitySpots()
    .then(() => {
      console.log("Activity spots seeding completed");
      process.exit(0);
    })
    .catch((error) => {
      console.error("Seeding failed:", error);
      process.exit(1);
    });
}
